### ISSUE TITLE
Introduce status priority to only print out one message at a time

### ISSUE THREAD

**Issue by sed-i** [PietroPasotti/compound-status#2]
Compounding in the backend is great, but probably not as helpful in the message itself: I think we want only one message at a time, and for it to be descriptive. Maybe introduce status priority?

**Comment by PietroPasotti** [comment]
The reasoning we followed was:
- if there are three blocked things, you'd want to know that there's three blocked things
- since there may be many, many things going on (if you have a status per relation like #1 requests, for example), the best we can hope for the status message to achieve is to show an overview and point the user to the debug-log, where more extensive information will be available.

I'd even consider having it switch after a certain amount of statuses to a 'summarized' presentation like:
(blocked:35); (waiting:12); (active: 140).

As it is now, it scales poorly with many statuses.

**Comment by sed-i** [comment]
- Practically, for the admin, there is no difference between `(blocked:35); (waiting:12); (active: 140)` and `BlockedStatus("See debug-log")` - both are vague just the same.
- Sifting through debug-log is tedious. I think it's much more ergonomic to for the admin to be instructed about what to fix next, one item at a time.
- Typically, when one problem is solved (e.g. pebble not yet ready), all the others go away right away.

**Comment by PietroPasotti** [comment]
fixed/addressed in v0.3

The default behaviour is now:
show only the 'worst' status among all the child statuses.

What is worst is obtained by sorting first by 'status name', where the ordering is (best to worst):
`"unknown", "active", "maintenance", "waiting", "blocked"`

Secondly we sort by priority, a numerical, user-given value. 
Therefore a waiting status with high priority will always be less relevant than a blocked status with low priority. We can discuss further whether this is desirable and how to make a total ordering out of this.

**Comment by sed-i** [comment]
> 'there's nothing we can tell about this unit, because it doesn't exist yet'.

Sounds like OF should prevent users from manually setting a unit's status to Unknown. Otherwise it will be used for other things eventually, just because it's available.

>  Status gets created in unknown and until someone sets it to something else, it's not interesting to surface it to the user.

Haven't looked at the impl, but would it make sense to have statuses start as None instead, and have Active at a lower priority than Unknown?

**Comment by PietroPasotti** [comment]
> Sounds like OF should prevent users from manually setting a unit's status to Unknown. Otherwise it will be used for other things eventually, just because it's available.

As it happens, OF *does forbid* users from setting the status to unknown. With StatusPool things are a bit different because we want to allow users to tell to the pool: forget about this status, it's no longer relevant. So, while (for simmetry) we don't allow `self.status_pool.foo = UnknownStatus('')`, we have `self.status_pool.foo.unset()` which does under the hood something equivalent to that.

> Haven't looked at the impl, but would it make sense to have statuses start as None instead, and have Active at a lower priority than Unknown?

That would make sense to me, I just don't see the difference yet between letting the status be None and setting it to Unknown. Could you give me a usage example?

It may well be that the Unit.status semantics is different from the StatusPool.Status semantics, so we need more nuanced variations (or totally different categories) than the existing Active/Waiting/Blocked/... Maybe we want totally custom statuses and priority orderings?
Maybe we want 'happy/unhappy' and that's it?

**Comment by pengale** [comment]
I think that, in this case, status `None` and status `Unknown` are semantically the same, and what @PietroPasotti is doing is fine, especially if "unset" kicks the unit into "Unknown" status.

We should include a comment summing up this conversation, as well as a line in the documentation about charm authors never needing to manually set status to "Unknown."

I don't think that we need to worry about it too much beyond that.

**Comment by PietroPasotti** [comment]
Added a clarification to the Readme
