### ISSUE TITLE
Fix usage of `__setattr__` not assigning the value

### ISSUE THREAD

**Issue by ghislainbourgeois** [PietroPasotti/compound-status#24]
In `StatusPool`, the overridden `__setattr__` will not set the attribute to the value passed, but to another computed value. This breaks the expected invariant:

```
my_status = ActiveStatus()
status_pool.workload = my_status
if status_pool.workload == my_status:
   print("Ok")
else:
   print("Wat")
```

I have some ideas on how to implement this and will probably give it a go in the next few days. It will however be a potentially breaking change for clients.

**Comment by PietroPasotti** [comment]
The reason for this design choice was 
1) I wanted to maintain consistency with the way we set status in ops (`self.unit.status = ActiveStatus('foo')`) while
2) allowing to idiomatically address statuses in the pool and do stuff like `self.pool.my_status.unset()` and `self.pool.my_status.log('bar')`.

I'm willing to sacrifice 2) if you think that this is "too unexpected" to be worth the trouble.

An alternative API could be:
```
self.pool.my_status = ActiveStatus('foo')  
# equivalent to `self.pool.add_status("my_status", ActiveStatus('foo'))`

assert self.pool.my_status == ActiveStatus('foo')  # ok
assert isinstance(self.pool.my_status, ActiveStatus)  # ok
self.pool.unset('my_status')
```

What is it that you were trying to do, which made you bump into this issue? 
Was it an equality check? Could we override Status.__eq__ so that only Tuple(message, name) are compared (and that check would pass)?

**Comment by ghislainbourgeois** [comment]
There were two things I wanted to do that this made difficult.

1. Unit testing in a complex charm, where the reason to get `CompoundStatus` was to try and reduce complexity. Workarounds include testing the overall status, which brings back the complexity in the test case, or to test the status based on the transformation done by `__setattr__`, which is brittle by depending on implementation details, and hard to read for developers not familiar with the internals of the library.
2. Inside the charm itself to simplify the logic. I wanted to specifically be able to compare the status of a relation. This use case is easy to design another way however.

In both cases, I was going for an equality check, so overriding `__eq__` could also work. 

My biggest concern is around broken expectations. It is expected that after assigning something to an attribute, reading from that attribute will get you back what you assigned.

I think it would be great if we could keep the nice API for `unset()/log()`.

I am not too sure what the best course of action would be here, I would be happy to get more input on this. I will also take some time to reflect more on this.
